//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurii_Bel_IT31
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ТеплосетиEntities : DbContext
    {
        public ТеплосетиEntities()
            : base("name=ТеплосетиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<ВидСети> ВидСети { get; set; }
        public DbSet<Должность> Должность { get; set; }
        public DbSet<ПослужнойСписок> ПослужнойСписок { get; set; }
        public DbSet<ПотребительТепла> ПотребительТепла { get; set; }
        public DbSet<Предприятие> Предприятие { get; set; }
        public DbSet<Сотрудник> Сотрудник { get; set; }
        public DbSet<СтальнаяТруба> СтальнаяТруба { get; set; }
        public DbSet<ТепловаяСеть> ТепловаяСеть { get; set; }
        public DbSet<ТепловойКолодец> ТепловойКолодец { get; set; }
        public DbSet<ТепловойПункт> ТепловойПункт { get; set; }
        public DbSet<УзелСети> УзелСети { get; set; }
        public DbSet<УчастокТрубопровода> УчастокТрубопровода { get; set; }
    }
}
