//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurii_Bel_IT31
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ВидСети
    {
        public ВидСети()
        {
            this.ТепловаяСеть = new HashSet<ТепловаяСеть>();
        }
    
        public int НомерВида { get; set; }
        public string НаименованиеВида { get; set; }
    
        public virtual ICollection<ТепловаяСеть> ТепловаяСеть { get; set; }
    }
}
