//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurii_Bel_IT31
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТепловаяСеть
    {
        public ТепловаяСеть()
        {
            this.УзелСети = new HashSet<УзелСети>();
        }
    
        public int НомерСети { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> КодПредприятия { get; set; }
        public Nullable<int> НомерВида { get; set; }
    
        public virtual ВидСети ВидСети { get; set; }
        public virtual Предприятие Предприятие { get; set; }
        public virtual ICollection<УзелСети> УзелСети { get; set; }
    }
}
