//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurii_Bel_IT31
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчастокТрубопровода
    {
        public Nullable<int> НомерТрубы { get; set; }
        public int НомерУчастка { get; set; }
        public Nullable<int> Длина { get; set; }
        public Nullable<int> Диаметр { get; set; }
        public Nullable<int> Толщина { get; set; }
        public Nullable<System.DateTime> ДатаПоследнегоРемонта { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<int> НомерУзлаНачала { get; set; }
        public Nullable<int> НомерУзлаКонца { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual СтальнаяТруба СтальнаяТруба { get; set; }
        public virtual УзелСети УзелСети { get; set; }
        public virtual УзелСети УзелСети1 { get; set; }
    }
}
